version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile  # Path to the frontend Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app  # Mount the frontend folder for live updates
    networks:
      - faq-net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile  # Path to the backend Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env  # Correct path to the backend .env file
    volumes:
      - ./backend:/app  # Mount the whole backend folder, not just ./backend/src
    depends_on:
      - db  # Wait for db to be ready before starting backend
    networks:
      - faq-net

  db:
    image: postgres:latest  # Using the latest PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@Asdf
      POSTGRES_DB: faq_service_db
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data between container restarts
    networks:
      - faq-net
    ports:
      - "5432:5432"  # Expose PostgreSQL port

networks:
  faq-net:
    driver: bridge

volumes:
  db_data:
